
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'A', '电子商品', '');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'B', '服装衣帽', '');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'C', 'qqqq', '');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'D', 'wwww', '');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'E', 'eeeee', '');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'F', 'rrrrr', '');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'G', 'ttttt', '');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'H', 'yyyyy', '');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'I', 'uuuuu', '');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'J', 'iiiii','');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'K', 'ooooo','');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'L', 'ppppp','');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'M', 'aaaaa','');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'N', 'sssss','');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'O', 'ddddd','');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'P', 'fffff','');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'Q', 'ggggg','');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'R', 'hhhhh','');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'S', 'jjjjj','');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'T', 'kkkkk','');
INSERT INTO `category_bigtype` (`category_type`,`category_typedesc`,`category_img`)VALUES( 'U', 'LLLLL','');




INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000001', '家电','A','0');    
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000002', '厨房电器','A','0');    
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000003', '生活电器','A','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000004', '手机','B','0');    
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000005', '数码','B','0');  
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000006', '电脑','B','0');    
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000007', '办公','B','0');    
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000008', '化妆品','C','0');    
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000009', '护肤','C','0');    
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000010', '护理','C','0');    
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000011', '女装','D','0');    
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000012', '内衣','D','0');  
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000013', '饰品','D','0');  
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000014', '男装','E','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000015', '户外用品','E','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000016', '运动','E','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000017', '女鞋','F','0'); 
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000018', '男鞋','F','0');    
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000019', '童鞋','F','0');    
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000020', '皮具','F','0');       
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000021', '童装','G','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000022', '母婴用品','G','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000023', '玩具','G','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000024', '腕表','H','0'); 
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000025', '眼镜','H','0'); 
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000026', '珠宝首饰','H','0');    
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000027', '家纺','I','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000028', '布艺','I','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000029', '家饰','I','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000030', '家具','J','0'); 
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000031', '建材','J','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000032', '卫浴','J','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000033', '灯饰','J','0');   
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000034', '厨具餐具','K','0'); 
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000035', '收纳','K','0'); 
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000036', '清洁','K','0'); 
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000037', '食品','L','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000038', '酒水','L','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000039', '粮油','L','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000040', '生鲜','L','0');    
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000041', '保健品','M','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000042', '滋补品','M','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000043', '礼品','M','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000044', '汽车','N','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000045', '配件','N','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000046', '车载电器','N','0');    
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000047', '全球','O','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000048', '跨境','O','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000049', '国家馆','O','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000050', '超市','P','0');  
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000051', '便利店','P','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000052', '生活服务','P','0');  
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000053', '全球','Q','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000054', '跨境','Q','0');
INSERT INTO `shop_category`(`category_id`,`category_name`,`category_type`,`category_pid`) VALUES ('C00000055', '国家馆','Q','0');


